version: '3.9'
services:
  app:
    restart: always
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    volumes:
      - data:/data
    env_file:
      - .env
    command: minio server /data/minio/

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - app
  redis:
    restart: always
    image: redis:7.0-alpine
    
volumes:
  postgres-data:
  data:
  