version: '3.9'
services:
  app:
    restart: always
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
      - redis
      - mailpit
  worker:
    restart: always
    build: .
    command: celery -A app worker -l INFO
    env_file:
      - .env
    depends_on:
      - app

  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    volumes:
      - minio-data:/minio-data
    env_file:
      - .env
    command: minio server /minio-data/minio/

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - app
  redis:
    restart: always
    image: redis:7.0-alpine

  mailpit:
    image: axllent/mailpit
    restart: always
    volumes:
      - ./mailpit-data:/mailpit-data
    ports:
      - 8025:8025
      - 1025:1025
    env_file:
      - .env

  # mailhog:
  #     image: mailhog/mailhog
  #     container_name: mailhog
  #     logging:
  #         driver: 'none' # disable saving logs
  #     ports:
  #         - 1025:1025 # smtp server
  #         - 8025:8025 # web ui
    
volumes:
  postgres-data:
  minio-data:
  