version: '3.9'
services:
  app:
    restart: always
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    volumes:
      - data:/data
    env_file:
      - .env
    command: minio server /data/minio/

volumes:
  postgres-data:
  data:
  