# Generated by Django 4.2.6 on 2023-11-24 17:41

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations
from django.db import models

from ..utils import fill_county_table


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("avatar", models.ImageField(upload_to="")),
                ("birthday", models.DateField(default=None, null=True)),
                ("is_active_email", models.BooleanField(default=False)),
                ("language", models.CharField(choices=[("EN", "en"), ("RU", "ru")], default="EN", max_length=2)),
                (
                    "country",
                    models.ForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="users.country"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.RunPython(fill_county_table),
    ]
