# Generated by Django 4.2.6 on 2024-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="done_tests",
            field=models.ManyToManyField(blank=True, to="quizzes.test"),
        ),
    ]
