# Generated by Django 4.2.6 on 2023-11-19 14:51

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_delete_image_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
    ]
