# Generated by Django 4.2.6 on 2023-11-19 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_is_active_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="registration_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
