# Generated by Django 4.2.6 on 2023-11-14 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0004_profilemodel_delete_image_delete_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileModel",
            new_name="Profile",
        ),
    ]
