# Generated by Django 4.2.6 on 2024-02-18 18:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttemptPipeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_start", models.DateTimeField(auto_now_add=True)),
                ("time_end", models.DateTimeField(null=True)),
                ("is_attempt_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AttemptState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice_text", models.CharField(max_length=256)),
                ("right_answer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=256)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=256)),
                ("time_for_complete", models.DurationField()),
                ("attempts", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_hidden", models.BooleanField(default=False)),
            ],
        ),
    ]
