# Generated by Django 4.2.6 on 2024-02-09 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quizzes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teststate",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="testpipeline",
            name="test",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizzes.test"),
        ),
        migrations.AddField(
            model_name="testpipeline",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="test",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="test",
            name="tag",
            field=models.ManyToManyField(blank=True, to="quizzes.tag"),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizzes.test"),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizzes.question"),
        ),
    ]
