# Generated by Django 4.2.6 on 2024-03-03 19:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="quizzes.test"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="attempts",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="test",
            name="is_hidden",
            field=models.BooleanField(default=True),
        ),
    ]
