# Generated by Django 4.2.6 on 2024-03-05 12:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_test_status_alter_question_test_alter_test_attempts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="status",
        ),
        migrations.AddField(
            model_name="test",
            name="has_first_attempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attemptstate",
            name="answer",
            field=models.CharField(),
        ),
    ]
