# Generated by Django 4.2.6 on 2024-03-08 12:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0004_remove_test_status_test_has_first_attempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptstate",
            name="is_right",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
