# Generated by Django 4.2.6 on 2024-03-12 16:31

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0005_attemptstate_is_right"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptstate",
            name="answer",
            field=models.JSONField(null=True, verbose_name="answer_id"),
        ),
        migrations.AlterField(
            model_name="attemptstate",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pipelines", to="quizzes.attemptpipeline"
            ),
        ),
        migrations.AlterField(
            model_name="attemptstate",
            name="is_right",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="choices", to="quizzes.question"
            ),
        ),
    ]
