# Generated by Django 4.2.6 on 2024-03-14 11:36

import datetime

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0006_alter_attemptstate_answer_alter_attemptstate_attempt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="time_for_complete",
            field=models.DurationField(
                validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3540))]
            ),
        ),
    ]
